//! Agent configuration: one TOML file owns everything operational.
//!
//! The file is the source of truth (docs/agent-design.md): watches,
//! per-host deploy flags, the API socket, the optional TCP listener,
//! and notification targets. On NixOS the file is generated by the
//! `nixosModules.deptui-agent` module and lives read-only in the store,
//! which is why the API deliberately has no config-editing surface.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::str::FromStr;
use std::time::Duration;

use anyhow::{anyhow, bail, Context, Result};
use serde::Deserialize;

use deptui_core::deploy::{Mode, ProfileSel, Toggles};
use deptui_core::ssh::SshOverride;

/// Default config path when neither `--config` nor
/// `$DEPTUI_AGENT_CONFIG` is set.
pub const DEFAULT_CONFIG_PATH: &str = "/etc/deptui-agent/config.toml";
/// Default control-socket path (`RuntimeDirectory=deptui-agent`).
pub const DEFAULT_SOCKET_PATH: &str = "/run/deptui-agent/agent.sock";
/// Default state directory (`StateDirectory=deptui-agent`).
pub const DEFAULT_STATE_DIR: &str = "/var/lib/deptui-agent";

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentConfig {
    /// Unix socket the control API listens on.
    #[serde(default = "default_socket")]
    pub socket: PathBuf,
    /// Where clones, state.json, and run logs live.
    #[serde(default = "default_state_dir")]
    pub state_dir: PathBuf,
    /// Optional TCP listener exposing *only* kick + status, for CI.
    #[serde(default)]
    pub listen: Option<ListenConfig>,
    #[serde(default)]
    pub notify: NotifyConfig,
    /// The repositories to watch. TOML `[[watch]]` tables.
    #[serde(default, rename = "watch")]
    pub watches: Vec<WatchConfig>,
}

fn default_socket() -> PathBuf {
    PathBuf::from(DEFAULT_SOCKET_PATH)
}

fn default_state_dir() -> PathBuf {
    PathBuf::from(DEFAULT_STATE_DIR)
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ListenConfig {
    /// e.g. `"0.0.0.0:7337"`.
    pub addr: String,
    /// File containing the bearer token. Read at startup; never inline
    /// in the config so the NixOS module can keep secrets out of the
    /// store.
    pub token_file: PathBuf,
}

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NotifyConfig {
    /// Hook command run on failure via `sh -c`. `{event}`, `{watch}`,
    /// `{host}`, `{rev}`, `{message}` are substituted (shell-quoted) and
    /// also exported as `DEPTUI_EVENT` etc.
    #[serde(default)]
    pub on_failure: Option<String>,
    /// Webhook URL. POSTed per event according to `kind`.
    #[serde(default)]
    pub url: Option<String>,
    /// `"ntfy"` (title/body/priority headers) or `"json"` (documented
    /// JSON schema). Defaults to `"json"`.
    #[serde(default)]
    pub kind: Option<String>,
    /// Optional bearer token file for the webhook.
    #[serde(default)]
    pub token_file: Option<PathBuf>,
    /// Which events fire the webhook. `failure` is always included;
    /// `start` and `success` are opt-in.
    #[serde(default)]
    pub events: Vec<String>,
}

impl NotifyConfig {
    pub fn webhook_kind(&self) -> WebhookKind {
        match self.kind.as_deref() {
            Some("ntfy") => WebhookKind::Ntfy,
            _ => WebhookKind::Json,
        }
    }

    /// Should this event kind reach the webhook? Failures (and
    /// unreachable warnings) always do; start/success only when opted
    /// in via `events`.
    pub fn wants_event(&self, kind: &str) -> bool {
        match kind {
            "failure" | "unreachable" => true,
            other => self.events.iter().any(|e| e == other),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WebhookKind {
    Ntfy,
    Json,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WatchConfig {
    pub name: String,
    /// Git URL or local path. Anything `git clone` accepts.
    pub repo: String,
    /// Watch a branch head…
    #[serde(default)]
    pub branch: Option<String>,
    /// …or a moving tag. Exactly one of the two.
    #[serde(default)]
    pub tag: Option<String>,
    /// Plain duration between polls, e.g. `"15m"`, `"1h30m"`.
    #[serde(default)]
    pub interval: Option<String>,
    /// Cron expression alternative (sec min hour dom mon dow year — the
    /// `cron` crate's 6/7-field form; 5-field crontab style is padded
    /// with a leading `0` for seconds).
    #[serde(default)]
    pub cron: Option<String>,
    /// How often to re-probe hosts that were offline when an update
    /// should have reached them (see `HostConfig::catch_up`). Duration
    /// string; default "2m".
    #[serde(default)]
    pub offline_recheck: Option<String>,
    /// Hosts to push to, keyed by the node name in `deploy.nodes`.
    /// Deployed sequentially in the order given by the map (BTreeMap:
    /// alphabetical — predictable, if not configurable yet).
    #[serde(default)]
    pub hosts: BTreeMap<String, HostConfig>,
}

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HostConfig {
    /// `"all"` (default), `"system"`, or `"home"`.
    #[serde(default)]
    pub profile: Option<String>,
    /// `"switch"` (default) or `"boot"`. `dry-run` is pointless for an
    /// unattended agent and not accepted.
    #[serde(default)]
    pub mode: Option<String>,
    /// deploy-rs flag overrides. Omitted keys follow deploy-rs's own
    /// defaults, mirroring the TUI's only-emit-if-changed rule.
    #[serde(default)]
    pub skip_checks: Option<bool>,
    #[serde(default)]
    pub magic_rollback: Option<bool>,
    #[serde(default)]
    pub auto_rollback: Option<bool>,
    #[serde(default)]
    pub remote_build: Option<bool>,
    /// Rejected with an explicit error: the agent is headless, there is
    /// nobody to type a sudo password. Present as a field so the error
    /// message can explain rather than "unknown field".
    #[serde(default)]
    pub interactive_sudo: Option<bool>,
    /// When the host is down at deploy time, remember the update and
    /// push it as soon as the agent sees the host answer again
    /// (default true). Off: the deploy is attempted anyway and a dead
    /// host records a normal failure, parking it until the next
    /// revision.
    #[serde(default)]
    pub catch_up: Option<bool>,
    /// Extra arguments forwarded to `nix build` via deploy-rs's `--`
    /// tail.
    #[serde(default)]
    pub extra_build_args: Vec<String>,
    /// Per-host SSH override, same semantics as the TUI's.
    #[serde(default)]
    pub ssh: Option<SshConfig>,
}

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SshConfig {
    #[serde(default)]
    pub hostname: Option<String>,
    #[serde(default)]
    pub user: Option<String>,
    #[serde(default)]
    pub identity: Option<PathBuf>,
    /// Free-form `-o` options, whitespace-separated.
    #[serde(default)]
    pub extra_opts: Option<String>,
}

impl HostConfig {
    pub fn profile_sel(&self) -> Result<ProfileSel> {
        match self.profile.as_deref() {
            None | Some("all") => Ok(ProfileSel::All),
            Some("system") => Ok(ProfileSel::System),
            Some("home") => Ok(ProfileSel::Home),
            Some(other) => bail!("unknown profile `{other}` (expected all/system/home)"),
        }
    }

    pub fn deploy_mode(&self) -> Result<Mode> {
        match self.mode.as_deref() {
            None | Some("switch") => Ok(Mode::Switch),
            Some("boot") => Ok(Mode::Boot),
            Some(other) => bail!("unknown mode `{other}` (expected switch/boot)"),
        }
    }

    pub fn toggles(&self) -> Toggles {
        let mut t = Toggles::default();
        if let Some(v) = self.skip_checks {
            t.skip_checks = v;
        }
        if let Some(v) = self.magic_rollback {
            t.magic_rollback = v;
        }
        if let Some(v) = self.auto_rollback {
            t.auto_rollback = v;
        }
        if let Some(v) = self.remote_build {
            t.remote_build = v;
        }
        t
    }

    // Wired up by the offline catch-up runner/daemon work; the knob
    // ships first so the config surface is stable. Remove the allow
    // when the runner reads it.
    #[allow(dead_code)]
    pub fn catch_up(&self) -> bool {
        self.catch_up.unwrap_or(true)
    }

    pub fn ssh_override(&self) -> SshOverride {
        let Some(ssh) = &self.ssh else {
            return SshOverride::default();
        };
        SshOverride {
            hostname: ssh.hostname.clone(),
            user: ssh.user.clone(),
            identity: ssh.identity.clone(),
            extra_opts: ssh.extra_opts.clone(),
        }
    }
}

/// The parsed poll cadence of one watch.
#[derive(Debug, Clone)]
pub enum Cadence {
    Every(Duration),
    Cron(Box<cron::Schedule>),
}

impl WatchConfig {
    /// The refspec `git ls-remote` should resolve.
    pub fn refspec(&self) -> String {
        match (&self.branch, &self.tag) {
            (Some(b), _) => format!("refs/heads/{b}"),
            (_, Some(t)) => format!("refs/tags/{t}"),
            _ => unreachable!("validated at load"),
        }
    }

    /// Human label for the watched ref.
    pub fn ref_label(&self) -> String {
        match (&self.branch, &self.tag) {
            (Some(b), _) => format!("branch {b}"),
            (_, Some(t)) => format!("tag {t}"),
            _ => unreachable!("validated at load"),
        }
    }

    /// Recheck cadence for offline hosts with a pending update.
    pub fn offline_recheck(&self) -> Result<Duration> {
        match &self.offline_recheck {
            Some(s) => parse_duration(s)
                .with_context(|| format!("watch `{}`: offline_recheck", self.name)),
            None => Ok(Duration::from_secs(120)),
        }
    }

    pub fn cadence(&self) -> Result<Cadence> {
        match (&self.interval, &self.cron) {
            (Some(i), None) => Ok(Cadence::Every(parse_duration(i)?)),
            (None, Some(c)) => {
                // Accept classic 5-field crontab lines by padding the
                // seconds column the `cron` crate requires.
                let padded;
                let expr = if c.split_whitespace().count() == 5 {
                    padded = format!("0 {c}");
                    &padded
                } else {
                    c.as_str()
                };
                let sched = cron::Schedule::from_str(expr)
                    .with_context(|| format!("watch `{}`: invalid cron `{c}`", self.name))?;
                Ok(Cadence::Cron(Box::new(sched)))
            }
            (Some(_), Some(_)) => bail!(
                "watch `{}`: `interval` and `cron` are mutually exclusive",
                self.name
            ),
            (None, None) => bail!(
                "watch `{}`: one of `interval` or `cron` is required",
                self.name
            ),
        }
    }
}

/// Parse `"90s"`, `"15m"`, `"1h30m"`, `"1d"` into a duration.
pub fn parse_duration(s: &str) -> Result<Duration> {
    let mut total = 0u64;
    let mut num = String::new();
    let mut saw_unit = false;
    for ch in s.trim().chars() {
        if ch.is_ascii_digit() {
            num.push(ch);
        } else {
            let n: u64 = num.parse().map_err(|_| anyhow!("invalid duration `{s}`"))?;
            num.clear();
            saw_unit = true;
            total += match ch {
                's' => n,
                'm' => n * 60,
                'h' => n * 3600,
                'd' => n * 86_400,
                _ => bail!("invalid duration `{s}` (units: s/m/h/d)"),
            };
        }
    }
    if !num.is_empty() || !saw_unit {
        bail!("invalid duration `{s}` (expected e.g. \"15m\", \"1h30m\")");
    }
    if total == 0 {
        bail!("duration `{s}` must be non-zero");
    }
    Ok(Duration::from_secs(total))
}

impl AgentConfig {
    /// Load and validate. Every constraint the daemon relies on is
    /// checked here so the run loop can trust the config wholesale.
    pub fn load(path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("reading agent config {}", path.display()))?;
        let cfg: AgentConfig = toml::from_str(&text)
            .with_context(|| format!("parsing agent config {}", path.display()))?;
        cfg.validate()?;
        Ok(cfg)
    }

    pub fn validate(&self) -> Result<()> {
        let mut seen = std::collections::BTreeSet::new();
        for w in &self.watches {
            if w.name.is_empty()
                || !w
                    .name
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
            {
                bail!("watch name `{}` must be non-empty [A-Za-z0-9_-]", w.name);
            }
            if !seen.insert(&w.name) {
                bail!("duplicate watch name `{}`", w.name);
            }
            if w.branch.is_some() == w.tag.is_some() {
                bail!(
                    "watch `{}`: exactly one of `branch` or `tag` is required",
                    w.name
                );
            }
            w.cadence()?;
            w.offline_recheck()?;
            if w.hosts.is_empty() {
                bail!("watch `{}` has no hosts configured", w.name);
            }
            for (host, hc) in &w.hosts {
                hc.profile_sel()
                    .with_context(|| format!("watch `{}` host `{host}`", w.name))?;
                hc.deploy_mode()
                    .with_context(|| format!("watch `{}` host `{host}`", w.name))?;
                if hc.interactive_sudo.is_some() {
                    bail!(
                        "watch `{}` host `{host}`: `interactive_sudo` is not available in the \
                         agent — it is headless, there is nobody to type a sudo password. \
                         Targets must accept non-interactive activation (root deploy user or \
                         NOPASSWD sudo)",
                        w.name
                    );
                }
            }
        }
        if let Some(n) = &self.notify.kind {
            if n != "ntfy" && n != "json" {
                bail!("notify.kind must be \"ntfy\" or \"json\", got `{n}`");
            }
        }
        for e in &self.notify.events {
            if !matches!(e.as_str(), "start" | "success" | "failure") {
                bail!("notify.events entries must be start/success/failure, got `{e}`");
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn minimal(extra: &str) -> String {
        format!(
            r#"
[[watch]]
name = "infra"
repo = "git@example.com:me/infra.git"
branch = "main"
interval = "15m"
{extra}
[watch.hosts.web]
"#
        )
    }

    #[test]
    fn minimal_config_parses() {
        let cfg: AgentConfig = toml::from_str(&minimal("")).unwrap();
        cfg.validate().unwrap();
        assert_eq!(cfg.socket, PathBuf::from(DEFAULT_SOCKET_PATH));
        assert_eq!(cfg.state_dir, PathBuf::from(DEFAULT_STATE_DIR));
        let w = &cfg.watches[0];
        assert_eq!(w.refspec(), "refs/heads/main");
        assert!(matches!(w.cadence().unwrap(), Cadence::Every(d) if d == Duration::from_secs(900)));
    }

    #[test]
    fn branch_and_tag_conflict() {
        let toml = minimal("").replace("branch = \"main\"", "branch = \"main\"\ntag = \"prod\"");
        let cfg: AgentConfig = toml::from_str(&toml).unwrap();
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn tag_refspec() {
        let toml = minimal("").replace("branch = \"main\"", "tag = \"prod\"");
        let cfg: AgentConfig = toml::from_str(&toml).unwrap();
        cfg.validate().unwrap();
        assert_eq!(cfg.watches[0].refspec(), "refs/tags/prod");
    }

    #[test]
    fn interactive_sudo_rejected_with_explanation() {
        let toml = minimal("").replace(
            "[watch.hosts.web]\n",
            "[watch.hosts.web]\ninteractive_sudo = true\n",
        );
        let cfg: AgentConfig = toml::from_str(&toml).unwrap();
        let err = cfg.validate().unwrap_err().to_string();
        assert!(err.contains("headless"), "unhelpful error: {err}");
    }

    #[test]
    fn five_field_cron_is_padded() {
        let toml = minimal("").replace("interval = \"15m\"", "cron = \"*/15 * * * *\"");
        let cfg: AgentConfig = toml::from_str(&toml).unwrap();
        cfg.validate().unwrap();
        assert!(matches!(
            cfg.watches[0].cadence().unwrap(),
            Cadence::Cron(_)
        ));
    }

    #[test]
    fn interval_and_cron_conflict() {
        let toml = minimal("cron = \"*/5 * * * *\"\n");
        // `extra` lands between interval and hosts; both keys present.
        let cfg: AgentConfig = toml::from_str(&toml).unwrap();
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn durations() {
        assert_eq!(parse_duration("90s").unwrap(), Duration::from_secs(90));
        assert_eq!(parse_duration("1h30m").unwrap(), Duration::from_secs(5400));
        assert_eq!(parse_duration("1d").unwrap(), Duration::from_secs(86_400));
        assert!(parse_duration("").is_err());
        assert!(parse_duration("15").is_err());
        assert!(parse_duration("0m").is_err());
        assert!(parse_duration("5x").is_err());
    }

    #[test]
    fn catch_up_defaults_on_and_can_be_disabled() {
        let cfg: AgentConfig = toml::from_str(&minimal("")).unwrap();
        assert!(cfg.watches[0].hosts["web"].catch_up());
        assert_eq!(
            cfg.watches[0].offline_recheck().unwrap(),
            Duration::from_secs(120)
        );

        let toml = minimal("offline_recheck = \"30s\"\n").replace(
            "[watch.hosts.web]\n",
            "[watch.hosts.web]\ncatch_up = false\n",
        );
        let cfg: AgentConfig = toml::from_str(&toml).unwrap();
        cfg.validate().unwrap();
        assert!(!cfg.watches[0].hosts["web"].catch_up());
        assert_eq!(
            cfg.watches[0].offline_recheck().unwrap(),
            Duration::from_secs(30)
        );

        let bad = minimal("offline_recheck = \"nope\"\n");
        let cfg: AgentConfig = toml::from_str(&bad).unwrap();
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn host_flags_overlay_deploy_rs_defaults() {
        let toml = minimal("").replace(
            "[watch.hosts.web]\n",
            "[watch.hosts.web]\nremote_build = true\nmagic_rollback = false\n",
        );
        let cfg: AgentConfig = toml::from_str(&toml).unwrap();
        let t = cfg.watches[0].hosts["web"].toggles();
        assert!(t.remote_build);
        assert!(!t.magic_rollback);
        // Untouched fields keep deploy-rs defaults.
        assert!(t.auto_rollback);
        assert!(!t.skip_checks);
    }
}
